import { profile } from "@/api/auth";
import { User } from "@/types";
import { SideBar } from "@/widgets/SideBar";
import React from "react";

export const metadata = {
  title: "Stomper | Admin Panel",
  description: "Generated by create next app",
};

export default async function AdminLayout({ children }) {
  const user: User = await profile();
  return (
    <>
      <SideBar user={user} />
      <div
        id="background-element"
        className="p-8 md:ml-60 min-h-screen bg-gray-200"
      >
        {children}
      </div>
    </>
  );
}
