import { AdminMiddleware } from "@/config/AdminMiddleware";
import { SideBar } from "@/widgets/SideBar";
import React from "react";

export const metadata = {
  title: "Stomper | Admin Panel",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <>
      <AdminMiddleware>
        <SideBar />
        <div
          id="background-element"
          className="p-8 md:ml-60 min-h-screen bg-gray-200"
        >
          {children}
        </div>
      </AdminMiddleware>
    </>
  );
}
